USE gestion_empleados;

INSERT INTO paises (codigo_pais, codigo_iso3_pais, nombre_pais, gentilicio_pais) VALUES
(4, 'AFG', 'Afganistán', 'Afgano/a'),
(248, 'ALA', 'Islas Åland', 'Alandés/esa'),
(8, 'ALB', 'Albania', 'Albanés/esa'),
(12, 'DZA', 'Argelia', 'Argelino/a'),
(20, 'AND', 'Andorra', 'Andorrano/a'),
(24, 'AGO', 'Angola', 'Angoleño/a'),
(28, 'ATG', 'Antigua y Barbuda', 'Antiguano/a'),
(32, 'ARG', 'Argentina', 'Argentino/a'),
(36, 'AUS', 'Australia', 'Australiano/a'),
(40, 'AUT', 'Austria', 'Austriaco/a'),
(31, 'AZE', 'Azerbaiyán', 'Azerbaiyano/a'),
(44, 'BHS', 'Bahamas', 'Bahameño/a'),
(48, 'BHR', 'Baréin', 'Bareiní'),
(50, 'BGD', 'Bangladesh', 'Bangladesí'),
(52, 'BRB', 'Barbados', 'Barbadense'),
(56, 'BEL', 'Bélgica', 'Belga'),
(84, 'BLZ', 'Belice', 'Beliceño/a'),
(204, 'BEN', 'Benín', 'Beninés/esa'),
(64, 'BTN', 'Bután', 'Butanés/esa'),
(68, 'BOL', 'Bolivia', 'Boliviano/a'),
(70, 'BIH', 'Bosnia y Herzegovina', 'Bosnio/a'),
(72, 'BWA', 'Botsuana', 'Botsuano/a'),
(76, 'BRA', 'Brasil', 'Brasileño/a'),
(96, 'BRN', 'Brunéi', 'Bruneano/a'),
(100, 'BGR', 'Bulgaria', 'Búlgaro/a'),
(854, 'BFA', 'Burkina Faso', 'Burkinés/esa'),
(108, 'BDI', 'Burundi', 'Burundés/esa'),
(132, 'CPV', 'Cabo Verde', 'Caboverdiano/a'),
(116, 'KHM', 'Camboya', 'Camboyano/a'),
(120, 'CMR', 'Camerún', 'Camerunés/esa'),
(124, 'CAN', 'Canadá', 'Canadiense'),
(140, 'CAF', 'República Centroafricana', 'Centroafricano/a'),
(148, 'TCD', 'Chad', 'Chadiano/a'),
(152, 'CHL', 'Chile', 'Chileno/a'),
(156, 'CHN', 'China', 'Chino/a'),
(170, 'COL', 'Colombia', 'Colombiano/a'),
(174, 'COM', 'Comoras', 'Comorense'),
(178, 'COG', 'Congo', 'Congoleño/a'),
(180, 'COD', 'República Democrática del Congo', 'Congoleño/a'),
(188, 'CRI', 'Costa Rica', 'Costarricense'),
(384, 'CIV', 'Costa de Marfil', 'Marfileño/a'),
(191, 'HRV', 'Croacia', 'Croata'),
(192, 'CUB', 'Cuba', 'Cubano/a'),
(196, 'CYP', 'Chipre', 'Chipriota'),
(203, 'CZE', 'Chequia', 'Checo/a'),
(208, 'DNK', 'Dinamarca', 'Danés/esa'),
(262, 'DJI', 'Yibuti', 'Yibutiano/a'),
(212, 'DMA', 'Dominica', 'Dominiqués/esa'),
(214, 'DOM', 'República Dominicana', 'Dominicano/a'),
(218, 'ECU', 'Ecuador', 'Ecuatoriano/a'),
(818, 'EGY', 'Egipto', 'Egipcio/a'),
(222, 'SLV', 'El Salvador', 'Salvadoreño/a'),
(226, 'GNQ', 'Guinea Ecuatorial', 'Ecuatoguineano/a'),
(232, 'ERI', 'Eritrea', 'Eritreo/a'),
(233, 'EST', 'Estonia', 'Estonio/a'),
(231, 'ETH', 'Etiopía', 'Etíope'),
(242, 'FJI', 'Fiyi', 'Fiyiano/a'),
(246, 'FIN', 'Finlandia', 'Finlandés/esa'),
(250, 'FRA', 'Francia', 'Francés/esa'),
(266, 'GAB', 'Gabón', 'Gabonés/esa'),
(270, 'GMB', 'Gambia', 'Gambiano/a'),
(268, 'GEO', 'Georgia', 'Georgiano/a'),
(276, 'DEU', 'Alemania', 'Alemán/ana'),
(288, 'GHA', 'Ghana', 'Ghanés/esa'),
(292, 'GIB', 'Gibraltar', 'Gibraltareño/a'),
(300, 'GRC', 'Grecia', 'Griego/a'),
(304, 'GRL', 'Groenlandia', 'Groenlandés/esa'),
(308, 'GRD', 'Granada', 'Granadino/a'),
(320, 'GTM', 'Guatemala', 'Guatemalteco/a'),
(324, 'GIN', 'Guinea', 'Guineano/a'),
(624, 'GNB', 'Guinea-Bisáu', 'Guineano/a'),
(328, 'GUY', 'Guyana', 'Guyanés/esa'),
(332, 'HTI', 'Haití', 'Haitiano/a'),
(340, 'HND', 'Honduras', 'Hondureño/a'),
(348, 'HUN', 'Hungría', 'Húngaro/a'),
(352, 'ISL', 'Islandia', 'Islandés/esa'),
(356, 'IND', 'India', 'Indio/a'),
(360, 'IDN', 'Indonesia', 'Indonesio/a'),
(364, 'IRN', 'Irán', 'Iraní'),
(368, 'IRQ', 'Irak', 'Iraquí'),
(372, 'IRL', 'Irlanda', 'Irlandés/esa'),
(376, 'ISR', 'Israel', 'Israelí'),
(380, 'ITA', 'Italia', 'Italiano/a'),
(388, 'JAM', 'Jamaica', 'Jamaicano/a'),
(392, 'JPN', 'Japón', 'Japonés/esa'),
(400, 'JOR', 'Jordania', 'Jordano/a'),
(398, 'KAZ', 'Kazajistán', 'Kazajo/a'),
(404, 'KEN', 'Kenia', 'Keniano/a'),
(296, 'KIR', 'Kiribati', 'Kiribatiano/a'),
(408, 'PRK', 'Corea del Norte', 'Norcoreano/a'),
(410, 'KOR', 'Corea del Sur', 'Surcoreano/a'),
(414, 'KWT', 'Kuwait', 'Kuwaití'),
(417, 'KGZ', 'Kirguistán', 'Kirguís'),
(418, 'LAO', 'Laos', 'Laosiano/a'),
(428, 'LVA', 'Letonia', 'Letón/ona'),
(422, 'LBN', 'Líbano', 'Libanés/esa'),
(426, 'LSO', 'Lesoto', 'Lesotense'),
(430, 'LBR', 'Liberia', 'Liberiano/a'),
(434, 'LBY', 'Libia', 'Libio/a'),
(438, 'LIE', 'Liechtenstein', 'Liechtensteiniano/a'),
(440, 'LTU', 'Lituania', 'Lituano/a'),
(442, 'LUX', 'Luxemburgo', 'Luxemburgués/esa'),
(450, 'MDG', 'Madagascar', 'Malgache'),
(454, 'MWI', 'Malaui', 'Malauí'),
(458, 'MYS', 'Malasia', 'Malasio/a'),
(462, 'MDV', 'Maldivas', 'Maldivo/a'),
(466, 'MLI', 'Malí', 'Maliense'),
(470, 'MLT', 'Malta', 'Maltés/esa'),
(584, 'MHL', 'Islas Marshall', 'Marshalés/esa'),
(478, 'MRT', 'Mauritania', 'Mauritano/a'),
(480, 'MUS', 'Mauricio', 'Mauriciano/a'),
(484, 'MEX', 'México', 'Mexicano/a'),
(583, 'FSM', 'Micronesia', 'Micronesio/a'),
(498, 'MDA', 'Moldavia', 'Moldavo/a'),
(492, 'MCO', 'Mónaco', 'Monegasco/a'),
(496, 'MNG', 'Mongolia', 'Mongol'),
(499, 'MNE', 'Montenegro', 'Montenegrino/a'),
(504, 'MAR', 'Marruecos', 'Marroquí'),
(508, 'MOZ', 'Mozambique', 'Mozambiqueño/a'),
(104, 'MMR', 'Myanmar', 'Birmano/a'),
(516, 'NAM', 'Namibia', 'Namibio/a'),
(520, 'NRU', 'Nauru', 'Nauruano/a'),
(524, 'NPL', 'Nepal', 'Nepalí'),
(528, 'NLD', 'Países Bajos', 'Neerlandés/esa'),
(540, 'NCL', 'Nueva Caledonia', 'Neocaledonio/a'),
(554, 'NZL', 'Nueva Zelanda', 'Neozelandés/esa'),
(558, 'NIC', 'Nicaragua', 'Nicaragüense'),
(562, 'NER', 'Níger', 'Nigerino/a'),
(566, 'NGA', 'Nigeria', 'Nigeriano/a'),
(570, 'NIU', 'Niue', 'Niuano/a'),
(578, 'NOR', 'Noruega', 'Noruego/a'),
(512, 'OMN', 'Omán', 'Omaní'),
(586, 'PAK', 'Pakistán', 'Pakistaní'),
(585, 'PLW', 'Palaos', 'Palauano/a'),
(275, 'PSE', 'Palestina', 'Palestino/a'),
(591, 'PAN', 'Panamá', 'Panameño/a'),
(598, 'PNG', 'Papúa Nueva Guinea', 'Papú'),
(600, 'PRY', 'Paraguay', 'Paraguayo/a'),
(604, 'PER', 'Perú', 'Peruano/a'),
(608, 'PHL', 'Filipinas', 'Filipino/a'),
(616, 'POL', 'Polonia', 'Polaco/a'),
(620, 'PRT', 'Portugal', 'Portugués/esa'),
(630, 'PRI', 'Puerto Rico', 'Puertorriqueño/a'),
(634, 'QAT', 'Catar', 'Qatarí'),
(642, 'ROU', 'Rumania', 'Rumano/a'),
(643, 'RUS', 'Rusia', 'Ruso/a'),
(646, 'RWA', 'Ruanda', 'Ruandés/esa'),
(654, 'SHN', 'Santa Elena', 'Santahelenense'),
(659, 'KNA', 'San Cristóbal y Nieves', 'Sancristobaleño/a'),
(662, 'LCA', 'Santa Lucía', 'Santalucense'),
(663, 'MAF', 'San Martín', 'Sanmartinense'),
(666, 'SPM', 'San Pedro y Miquelón', 'Sampedrino/a'),
(670, 'VCT', 'San Vicente y las Granadinas', 'Sanvicentino/a'),
(882, 'WSM', 'Samoa', 'Samoano/a'),
(674, 'SMR', 'San Marino', 'Sanmarinense'),
(678, 'STP', 'Santo Tomé y Príncipe', 'Santomense'),
(682, 'SAU', 'Arabia Saudita', 'Saudí'),
(686, 'SEN', 'Senegal', 'Senegalés/esa'),
(688, 'SRB', 'Serbia', 'Serbio/a'),
(690, 'SYC', 'Seychelles', 'Seychelense'),
(694, 'SLE', 'Sierra Leona', 'Sierraleonés/esa'),
(702, 'SGP', 'Singapur', 'Singapurense'),
(703, 'SVK', 'Eslovaquia', 'Eslovaco/a'),
(705, 'SVN', 'Eslovenia', 'Esloveno/a'),
(90, 'SLB', 'Islas Salomón', 'Salomonense'),
(706, 'SOM', 'Somalia', 'Somalí'),
(710, 'ZAF', 'Sudáfrica', 'Sudafricano/a'),
(728, 'SSD', 'Sudán del Sur', 'Sur Sudanés/esa'),
(724, 'ESP', 'España', 'Español/a'),
(144, 'LKA', 'Sri Lanka', 'Ceilanés/esa'),
(729, 'SDN', 'Sudán', 'Sudanés/esa'),
(740, 'SUR', 'Surinam', 'Surinamés/esa'),
(748, 'SWZ', 'Esuatini', 'Suazi'),
(752, 'SWE', 'Suecia', 'Sueco/a'),
(756, 'CHE', 'Suiza', 'Suizo/a'),
(760, 'SYR', 'Siria', 'Sirio/a'),
(762, 'TJK', 'Tayikistán', 'Tayiko/a'),
(834, 'TZA', 'Tanzania', 'Tanzano/a'),
(764, 'THA', 'Tailandia', 'Tailandés/esa'),
(626, 'TLS', 'Timor Oriental', 'Timorense'),
(768, 'TGO', 'Togo', 'Togolés/esa'),
(772, 'TKL', 'Tokelau', 'Tokelauano/a'),
(776, 'TON', 'Tonga', 'Tongano/a'),
(780, 'TTO', 'Trinidad y Tobago', 'Trinitense'),
(788, 'TUN', 'Túnez', 'Tunecino/a'),
(792, 'TUR', 'Turquía', 'Turco/a'),
(795, 'TKM', 'Turkmenistán', 'Turcomano/a'),
(796, 'TCA', 'Islas Turcas y Caicos', 'Turqueño/a'),
(798, 'TUV', 'Tuvalu', 'Tuvaluano/a'),
(800, 'UGA', 'Uganda', 'Ugandés/esa'),
(804, 'UKR', 'Ucrania', 'Ucraniano/a'),
(784, 'ARE', 'Emiratos Árabes Unidos', 'Emiratí'),
(826, 'GBR', 'Reino Unido', 'Británico/a'),
(840, 'USA', 'Estados Unidos', 'Estadounidense'),
(858, 'URY', 'Uruguay', 'Uruguayo/a'),
(860, 'UZB', 'Uzbekistán', 'Uzbeko/a'),
(548, 'VUT', 'Vanuatu', 'Vanuatuense'),
(862, 'VEN', 'Venezuela', 'Venezolano/a'),
(704, 'VNM', 'Vietnam', 'Vietnamita'),
(876, 'WLF', 'Wallis y Futuna', 'Futunense'),
(887, 'YEM', 'Yemen', 'Yemení'),
(894, 'ZMB', 'Zambia', 'Zambiano/a'),
(716, 'ZWE', 'Zimbabue', 'Zimbabuense');
INSERT INTO 

INSERT INTO tipos_empleado (tipo_empleado, descripcion_tipo_empleado) VALUES
('Administrador', 'Usuario administrador, control total del sistema.'),
('Gerente Departamento', 'Gerente de departamento, gestiona departamentos específicos.'),
('Administrativo', 'Empleado con funciones administrativas.')
('Técnico Operario', 'Empleado de especialización técnica.'),
('Operario', 'Empleado con funciones de asistencia no técnica.');

INSERT INTO 