USE gestion_empleados;

INSERT INTO paises (codigo_pais, codigo_iso3_pais, nombre_pais, gentilicio_pais) VALUES
(4, 'AFG', 'Afganistán', 'Afgano/a'),
(248, 'ALA', 'Islas Åland', 'Alandés/esa'),
(8, 'ALB', 'Albania', 'Albanés/esa'),
(12, 'DZA', 'Argelia', 'Argelino/a'),
(20, 'AND', 'Andorra', 'Andorrano/a'),
(24, 'AGO', 'Angola', 'Angoleño/a'),
(28, 'ATG', 'Antigua y Barbuda', 'Antiguano/a'),
(32, 'ARG', 'Argentina', 'Argentino/a'),
(36, 'AUS', 'Australia', 'Australiano/a'),
(40, 'AUT', 'Austria', 'Austriaco/a'),
(31, 'AZE', 'Azerbaiyán', 'Azerbaiyano/a'),
(44, 'BHS', 'Bahamas', 'Bahameño/a'),
(48, 'BHR', 'Baréin', 'Bareiní'),
(50, 'BGD', 'Bangladesh', 'Bangladesí'),
(52, 'BRB', 'Barbados', 'Barbadense'),
(56, 'BEL', 'Bélgica', 'Belga'),
(84, 'BLZ', 'Belice', 'Beliceño/a'),
(204, 'BEN', 'Benín', 'Beninés/esa'),
(64, 'BTN', 'Bután', 'Butanés/esa'),
(68, 'BOL', 'Bolivia', 'Boliviano/a'),
(70, 'BIH', 'Bosnia y Herzegovina', 'Bosnio/a'),
(72, 'BWA', 'Botsuana', 'Botsuano/a'),
(76, 'BRA', 'Brasil', 'Brasileño/a'),
(96, 'BRN', 'Brunéi', 'Bruneano/a'),
(100, 'BGR', 'Bulgaria', 'Búlgaro/a'),
(854, 'BFA', 'Burkina Faso', 'Burkinés/esa'),
(108, 'BDI', 'Burundi', 'Burundés/esa'),
(132, 'CPV', 'Cabo Verde', 'Caboverdiano/a'),
(116, 'KHM', 'Camboya', 'Camboyano/a'),
(120, 'CMR', 'Camerún', 'Camerunés/esa'),
(124, 'CAN', 'Canadá', 'Canadiense'),
(140, 'CAF', 'República Centroafricana', 'Centroafricano/a'),
(148, 'TCD', 'Chad', 'Chadiano/a'),
(152, 'CHL', 'Chile', 'Chileno/a'),
(156, 'CHN', 'China', 'Chino/a'),
(170, 'COL', 'Colombia', 'Colombiano/a'),
(174, 'COM', 'Comoras', 'Comorense'),
(178, 'COG', 'Congo', 'Congoleño/a'),
(180, 'COD', 'República Democrática del Congo', 'Congoleño/a'),
(188, 'CRI', 'Costa Rica', 'Costarricense'),
(384, 'CIV', 'Costa de Marfil', 'Marfileño/a'),
(191, 'HRV', 'Croacia', 'Croata'),
(192, 'CUB', 'Cuba', 'Cubano/a'),
(196, 'CYP', 'Chipre', 'Chipriota'),
(203, 'CZE', 'Chequia', 'Checo/a'),
(208, 'DNK', 'Dinamarca', 'Danés/esa'),
(262, 'DJI', 'Yibuti', 'Yibutiano/a'),
(212, 'DMA', 'Dominica', 'Dominiqués/esa'),
(214, 'DOM', 'República Dominicana', 'Dominicano/a'),
(218, 'ECU', 'Ecuador', 'Ecuatoriano/a'),
(818, 'EGY', 'Egipto', 'Egipcio/a'),
(222, 'SLV', 'El Salvador', 'Salvadoreño/a'),
(226, 'GNQ', 'Guinea Ecuatorial', 'Ecuatoguineano/a'),
(232, 'ERI', 'Eritrea', 'Eritreo/a'),
(233, 'EST', 'Estonia', 'Estonio/a'),
(231, 'ETH', 'Etiopía', 'Etíope'),
(242, 'FJI', 'Fiyi', 'Fiyiano/a'),
(246, 'FIN', 'Finlandia', 'Finlandés/esa'),
(250, 'FRA', 'Francia', 'Francés/esa'),
(266, 'GAB', 'Gabón', 'Gabonés/esa'),
(270, 'GMB', 'Gambia', 'Gambiano/a'),
(268, 'GEO', 'Georgia', 'Georgiano/a'),
(276, 'DEU', 'Alemania', 'Alemán/ana'),
(288, 'GHA', 'Ghana', 'Ghanés/esa'),
(292, 'GIB', 'Gibraltar', 'Gibraltareño/a'),
(300, 'GRC', 'Grecia', 'Griego/a'),
(304, 'GRL', 'Groenlandia', 'Groenlandés/esa'),
(308, 'GRD', 'Granada', 'Granadino/a'),
(320, 'GTM', 'Guatemala', 'Guatemalteco/a'),
(324, 'GIN', 'Guinea', 'Guineano/a'),
(624, 'GNB', 'Guinea-Bisáu', 'Guineano/a'),
(328, 'GUY', 'Guyana', 'Guyanés/esa'),
(332, 'HTI', 'Haití', 'Haitiano/a'),
(340, 'HND', 'Honduras', 'Hondureño/a'),
(348, 'HUN', 'Hungría', 'Húngaro/a'),
(352, 'ISL', 'Islandia', 'Islandés/esa'),
(356, 'IND', 'India', 'Indio/a'),
(360, 'IDN', 'Indonesia', 'Indonesio/a'),
(364, 'IRN', 'Irán', 'Iraní'),
(368, 'IRQ', 'Irak', 'Iraquí'),
(372, 'IRL', 'Irlanda', 'Irlandés/esa'),
(376, 'ISR', 'Israel', 'Israelí'),
(380, 'ITA', 'Italia', 'Italiano/a'),
(388, 'JAM', 'Jamaica', 'Jamaicano/a'),
(392, 'JPN', 'Japón', 'Japonés/esa'),
(400, 'JOR', 'Jordania', 'Jordano/a'),
(398, 'KAZ', 'Kazajistán', 'Kazajo/a'),
(404, 'KEN', 'Kenia', 'Keniano/a'),
(296, 'KIR', 'Kiribati', 'Kiribatiano/a'),
(408, 'PRK', 'Corea del Norte', 'Norcoreano/a'),
(410, 'KOR', 'Corea del Sur', 'Surcoreano/a'),
(414, 'KWT', 'Kuwait', 'Kuwaití'),
(417, 'KGZ', 'Kirguistán', 'Kirguís'),
(418, 'LAO', 'Laos', 'Laosiano/a'),
(428, 'LVA', 'Letonia', 'Letón/ona'),
(422, 'LBN', 'Líbano', 'Libanés/esa'),
(426, 'LSO', 'Lesoto', 'Lesotense'),
(430, 'LBR', 'Liberia', 'Liberiano/a'),
(434, 'LBY', 'Libia', 'Libio/a'),
(438, 'LIE', 'Liechtenstein', 'Liechtensteiniano/a'),
(440, 'LTU', 'Lituania', 'Lituano/a'),
(442, 'LUX', 'Luxemburgo', 'Luxemburgués/esa'),
(450, 'MDG', 'Madagascar', 'Malgache'),
(454, 'MWI', 'Malaui', 'Malauí'),
(458, 'MYS', 'Malasia', 'Malasio/a'),
(462, 'MDV', 'Maldivas', 'Maldivo/a'),
(466, 'MLI', 'Malí', 'Maliense'),
(470, 'MLT', 'Malta', 'Maltés/esa'),
(584, 'MHL', 'Islas Marshall', 'Marshalés/esa'),
(478, 'MRT', 'Mauritania', 'Mauritano/a'),
(480, 'MUS', 'Mauricio', 'Mauriciano/a'),
(484, 'MEX', 'México', 'Mexicano/a'),
(583, 'FSM', 'Micronesia', 'Micronesio/a'),
(498, 'MDA', 'Moldavia', 'Moldavo/a'),
(492, 'MCO', 'Mónaco', 'Monegasco/a'),
(496, 'MNG', 'Mongolia', 'Mongol'),
(499, 'MNE', 'Montenegro', 'Montenegrino/a'),
(504, 'MAR', 'Marruecos', 'Marroquí'),
(508, 'MOZ', 'Mozambique', 'Mozambiqueño/a'),
(104, 'MMR', 'Myanmar', 'Birmano/a'),
(516, 'NAM', 'Namibia', 'Namibio/a'),
(520, 'NRU', 'Nauru', 'Nauruano/a'),
(524, 'NPL', 'Nepal', 'Nepalí'),
(528, 'NLD', 'Países Bajos', 'Neerlandés/esa'),
(540, 'NCL', 'Nueva Caledonia', 'Neocaledonio/a'),
(554, 'NZL', 'Nueva Zelanda', 'Neozelandés/esa'),
(558, 'NIC', 'Nicaragua', 'Nicaragüense'),
(562, 'NER', 'Níger', 'Nigerino/a'),
(566, 'NGA', 'Nigeria', 'Nigeriano/a'),
(570, 'NIU', 'Niue', 'Niuano/a'),
(578, 'NOR', 'Noruega', 'Noruego/a'),
(512, 'OMN', 'Omán', 'Omaní'),
(586, 'PAK', 'Pakistán', 'Pakistaní'),
(585, 'PLW', 'Palaos', 'Palauano/a'),
(275, 'PSE', 'Palestina', 'Palestino/a'),
(591, 'PAN', 'Panamá', 'Panameño/a'),
(598, 'PNG', 'Papúa Nueva Guinea', 'Papú'),
(600, 'PRY', 'Paraguay', 'Paraguayo/a'),
(604, 'PER', 'Perú', 'Peruano/a'),
(608, 'PHL', 'Filipinas', 'Filipino/a'),
(616, 'POL', 'Polonia', 'Polaco/a'),
(620, 'PRT', 'Portugal', 'Portugués/esa'),
(630, 'PRI', 'Puerto Rico', 'Puertorriqueño/a'),
(634, 'QAT', 'Catar', 'Qatarí'),
(642, 'ROU', 'Rumania', 'Rumano/a'),
(643, 'RUS', 'Rusia', 'Ruso/a'),
(646, 'RWA', 'Ruanda', 'Ruandés/esa'),
(654, 'SHN', 'Santa Elena', 'Santahelenense'),
(659, 'KNA', 'San Cristóbal y Nieves', 'Sancristobaleño/a'),
(662, 'LCA', 'Santa Lucía', 'Santalucense'),
(663, 'MAF', 'San Martín', 'Sanmartinense'),
(666, 'SPM', 'San Pedro y Miquelón', 'Sampedrino/a'),
(670, 'VCT', 'San Vicente y las Granadinas', 'Sanvicentino/a'),
(882, 'WSM', 'Samoa', 'Samoano/a'),
(674, 'SMR', 'San Marino', 'Sanmarinense'),
(678, 'STP', 'Santo Tomé y Príncipe', 'Santomense'),
(682, 'SAU', 'Arabia Saudita', 'Saudí'),
(686, 'SEN', 'Senegal', 'Senegalés/esa'),
(688, 'SRB', 'Serbia', 'Serbio/a'),
(690, 'SYC', 'Seychelles', 'Seychelense'),
(694, 'SLE', 'Sierra Leona', 'Sierraleonés/esa'),
(702, 'SGP', 'Singapur', 'Singapurense'),
(703, 'SVK', 'Eslovaquia', 'Eslovaco/a'),
(705, 'SVN', 'Eslovenia', 'Esloveno/a'),
(90, 'SLB', 'Islas Salomón', 'Salomonense'),
(706, 'SOM', 'Somalia', 'Somalí'),
(710, 'ZAF', 'Sudáfrica', 'Sudafricano/a'),
(728, 'SSD', 'Sudán del Sur', 'Sur Sudanés/esa'),
(724, 'ESP', 'España', 'Español/a'),
(144, 'LKA', 'Sri Lanka', 'Ceilanés/esa'),
(729, 'SDN', 'Sudán', 'Sudanés/esa'),
(740, 'SUR', 'Surinam', 'Surinamés/esa'),
(748, 'SWZ', 'Esuatini', 'Suazi'),
(752, 'SWE', 'Suecia', 'Sueco/a'),
(756, 'CHE', 'Suiza', 'Suizo/a'),
(760, 'SYR', 'Siria', 'Sirio/a'),
(762, 'TJK', 'Tayikistán', 'Tayiko/a'),
(834, 'TZA', 'Tanzania', 'Tanzano/a'),
(764, 'THA', 'Tailandia', 'Tailandés/esa'),
(626, 'TLS', 'Timor Oriental', 'Timorense'),
(768, 'TGO', 'Togo', 'Togolés/esa'),
(772, 'TKL', 'Tokelau', 'Tokelauano/a'),
(776, 'TON', 'Tonga', 'Tongano/a'),
(780, 'TTO', 'Trinidad y Tobago', 'Trinitense'),
(788, 'TUN', 'Túnez', 'Tunecino/a'),
(792, 'TUR', 'Turquía', 'Turco/a'),
(795, 'TKM', 'Turkmenistán', 'Turcomano/a'),
(796, 'TCA', 'Islas Turcas y Caicos', 'Turqueño/a'),
(798, 'TUV', 'Tuvalu', 'Tuvaluano/a'),
(800, 'UGA', 'Uganda', 'Ugandés/esa'),
(804, 'UKR', 'Ucrania', 'Ucraniano/a'),
(784, 'ARE', 'Emiratos Árabes Unidos', 'Emiratí'),
(826, 'GBR', 'Reino Unido', 'Británico/a'),
(840, 'USA', 'Estados Unidos', 'Estadounidense'),
(858, 'URY', 'Uruguay', 'Uruguayo/a'),
(860, 'UZB', 'Uzbekistán', 'Uzbeko/a'),
(548, 'VUT', 'Vanuatu', 'Vanuatuense'),
(862, 'VEN', 'Venezuela', 'Venezolano/a'),
(704, 'VNM', 'Vietnam', 'Vietnamita'),
(876, 'WLF', 'Wallis y Futuna', 'Futunense'),
(887, 'YEM', 'Yemen', 'Yemení'),
(894, 'ZMB', 'Zambia', 'Zambiano/a'),
(716, 'ZWE', 'Zimbabue', 'Zimbabuense');

INSERT INTO tipos_empleado (tipo_empleado, descripcion_tipo_empleado) VALUES
('Administrador', 'Usuario administrador, control total del sistema.'),
('Gerente Departamento', 'Gerente de departamento, gestiona departamentos específicos.'),
('Administrativo', 'Empleado con funciones administrativas.'),
('Técnico Operario', 'Empleado de especialización técnica.'),
('Operario', 'Empleado con funciones de asistencia no técnica.');

INSERT INTO modulos (codigo_modulo, nombre_modulo, descripcion_modulo) VALUES
('RRHH', 'Gestión de Empleados', 'Creación y mantención de Empleados. Asociación con Departamentos y Proyectos.'),
('GCOM', 'Gestión Comercial', 'Creación y mantención de Clientes.'),
('GDEP', 'Gestión de Departamentos', 'Creación y mantención de Departamentos. Asociación con Gerentes.'),
('GPRO', 'Gestión de Proyectos', 'Creación y mantención de Proyectos. Asociación con Clientes.'),
('GINF', 'Generación de Informes', 'Creación y mantención de Informes.'),
('RHRS', 'Registro de Tiempo', 'Ingreso de horas trabajadas por proyectos específicos.'),
('GSIS', 'Gestión de Sistema', 'Configuración de Sistema. Creación y mantención de módulos y permisos.');

INSERT INTO roles (rol, descripcion_rol, permisos_rol) VALUES
('Administrador General', 'Control completo de sistema. Creación y mantención de módulos y permisos', 'RRHH,GCOM,GDEP,GPRO,GINF,RHRS,GSIS'),
('Administrador Comercial', 'Control comercial. Creación y mantención de clientes y relaciones comerciales.', 'RRHH,GCOM,GINF,RHRS'),
('Gerente de Área', 'Control completo de Departamentos.', 'RRHH,GDEP,GPRO,GINF,RHRS'),
('Técnico', 'Empleado de nivel técnico. Registro de horas trabajadas y generación de informes.', 'GINF,RHRS'),
('Operario', 'Empleado sin nivel técnico. Registro de horas trabajadas.', 'RHRS');

INSERT INTO empleados (rut_empleado, nombre_empleado, fecha_contrato, salario_empleado, correo_empleado, telefono_empleado, direccion_empleado, fecha_nacimiento_empleado, id_tipo_empleado, id_rol, codigo_pais) VALUES
('18755039-4',
    'Aquiles Baeza Parada',
    CURDATE(),
    4500000,
    'aquiles_baeza@gmail.com',
    '569123456',
    'Los Confines 123, Temuco',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 45 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Administrador'),
    (SELECT id_rol FROM roles WHERE rol = 'Administrador General'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('12258720-7',
    'Alan Brito Delgado',
    CURDATE(),
    3500000,
    'alan_brito@gmail.com',
    '569456789',
    'Guido Beck de Ramberga 456, Padre las Casas',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 40 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Gerente Departamento'),
    (SELECT id_rol FROM roles WHERE rol = 'Gerente de Área'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('4162738-7',
    'Patricio Donald',
    CURDATE(),
    2500000,
    'pato_donald@gmail.com',
    '569147258',
    '18 de Septiembre 258, Pitrufquén',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 35 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Administrativo'),
    (SELECT id_rol FROM roles WHERE rol = 'Administrador Comercial'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('15265109-0',
    'Susana Oria Naranja',
    CURDATE(),
    1500000,
    'susanaoria@gmail.com',
    '569258369',
    '21 de mayo 789, Padre las Casas',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 30 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Técnico Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Técnico'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('19327725-K',
    'Elba Lazo Fugaz',
    CURDATE(),
    1500000,
    'elba.lazo@gmail.com',
    '569789456',
    'Quinta Las Ilusiones 159, Carahue',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 30 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Técnico Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Técnico'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('11514618-1',
    'Armando Lios Fuertes',
    CURDATE(),
    1500000,
    'armandolf@gmail.com',
    '569987654',
    'John Kennedy 951, Villa Los Ríos, Temuco',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 30 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Técnico Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Técnico'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('5107955-8',
    'Zacarías Flores del Campo',
    CURDATE(),
    500000,
    'zacariasdelcampo@gmail.com',
    '569987654',
    'Martín Tenía un Violín 369, Villa Pedro de Valdivia, Temuco',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 25 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Operario'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('5794344-0',
    'Esteban Dido',
    CURDATE(),
    500000,
    'estebandido1999@gmail.com',
    '569654321',
    'Gladys Marín 357, Villa Pedro de Valdivia, Temuco',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 25 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Operario'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('5250197-0',
    'Zacarías Flores del Campo',
    CURDATE(),
    500000,
    'zacariasdelcampo@gmail.com',
    '569321654',
    'Los Girasoles 369, Villa las Azaleas, Metrenco',
    (SELECT DATE_SUB(CURDATE(), INTERVAL 25 YEAR)),
    (SELECT id_tipo_empleado FROM tipos_empleado WHERE tipo_empleado = 'Operario'),
    (SELECT id_rol FROM roles WHERE rol = 'Operario'),
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile'));

INSERT INTO departamentos (nombre_departamento, descripcion_departamento, id_empleado) VALUES
('RRHH', 'Departamento de Recursos Humanos', (SELECT id_empleado FROM empleados WHERE rut_empleado = '18755039-4')),
('ID', 'Investigación y Tecnología', (SELECT id_empleado FROM empleados WHERE rut_empleado = '12258720-7')),
('Comercial', 'Departamento de Gestión Comercial', (SELECT id_empleado FROM empleados WHERE rut_empleado = '18755039-4')),
('Mantención', 'Departamento de Mantención Interna', (SELECT id_empleado FROM empleados WHERE rut_empleado = '12258720-7'));

INSERT INTO empleados_departamento (id_empleado, id_departamento) VALUES
((SELECT id_empleado FROM empleados WHERE rut_empleado = '15265109-0'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '19327725-K'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '11514618-1'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '5107955-8'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'Mantención')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '5794344-0'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'Mantención')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '5250197-0'),(SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'Mantención'));

INSERT INTO clientes (rut_cliente, razon_social, correo_contacto, telefono_contacto, direccion_cliente, codigo_pais) VALUES
('6006374-5',
    'Tuerca Solutions',
    'contacto@tuercasolutions.cl',
    '56995127532',
    'Aldunate 525, Temuco',
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile')),
('9325475-9',
    'Teclazo Tech',
    'contact@teclazotech.com',
    '16302452364',
    '3038 Walkers Ridge Way, Naperville, IL 60563',
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Estados Unidos')),
('23225874-8',
    'Click Aquí S.A.',
    'contacto@clickaqui.cl',
    '56945678956',
    'Avenida Libertad 301, Viña del Mar',
    (SELECT codigo_pais FROM paises WHERE nombre_pais = 'Chile'));

INSERT INTO proyectos (nombre_proyecto, descripcion_proyecto, fecha_inicio_proyecto, id_cliente, id_departamento) VALUES
('Sistema Fotovoltaico Central',
    'Instalación de sistema fotovoltaico central para control operacional casa matriz.',
    CURDATE(),
    (SELECT id_cliente FROM clientes WHERE rut_cliente = '6006374-5'),
    (SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID')),
('HHRR Management',
    'HHRR Managing .Net System for Teclazo Tech International.',
    CURDATE(),
    (SELECT id_cliente FROM clientes WHERE rut_cliente = '9325475-9'),
    (SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID')),
('Gestión Inventario',
    'Desarrollo sistema de gestiín de inventario Click Aquí S.A.',
    CURDATE(),
    (SELECT id_cliente FROM clientes WHERE rut_cliente = '23225874-8'),
    (SELECT id_departamento FROM departamentos WHERE nombre_departamento = 'ID'));

INSERT INTO empleados_proyecto (id_empleado, id_proyecto) VALUES
((SELECT id_empleado FROM empleados WHERE rut_empleado = '15265109-0'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'HHRR Management')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '19327725-K'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'HHRR Management')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '11514618-1'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'HHRR Management')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '15265109-0'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'Gestión Inventario')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '19327725-K'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'Gestión Inventario')),
((SELECT id_empleado FROM empleados WHERE rut_empleado = '11514618-1'),(SELECT id_proyecto FROM proyectos WHERE nombre_proyecto = 'Gestión Inventario'));

INSERT INTO registros_tiempo (fecha_registro, tiempo_trabajado, tareas_realizadas, observaciones, id_empleado_proyecto) VALUES
(CURDATE(),
    4.0,
    'Creación repositorio y rama desarrollo.',
    'Creación repositorio github para aplicación. Creación de rama dedesarrollo. Incorporación colaboradores a rama desarrollo.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '15265109-0' AND P.nombre_proyecto = 'HHRR Management')),
(CURDATE(),
    4.0,
    'Recepción documentación. Inicio análisis requerimientos.',
    'Inicio análisis preliminar de requerimientos en base a documentación recibida.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '19327725-K' AND P.nombre_proyecto = 'HHRR Management')),
(CURDATE(),
    4.0,
    'Recepción documentación. Inicio análisis requerimientos.',
    'Inicio análisis preliminar de requerimientos en base a documentación recibida.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '11514618-1' AND P.nombre_proyecto = 'HHRR Management')),
(CURDATE(),
    4.0,
    'Creación repositorio y rama desarrollo.',
    'Creación repositorio github para aplicación. Creación de rama dedesarrollo. Incorporación colaboradores a rama desarrollo.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '15265109-0' AND P.nombre_proyecto = 'Gestión Inventario')),
(CURDATE(),
    4.0,
    'Recepción documentación. Inicio análisis requerimientos.',
    'Inicio análisis preliminar de requerimientos en base a documentación recibida.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '19327725-K' AND P.nombre_proyecto = 'Gestión Inventario')),
(CURDATE(),
    4.0,
    'Recepción documentación. Inicio análisis requerimientos.',
    'Inicio análisis preliminar de requerimientos en base a documentación recibida.',
    (SELECT EP.id_empleado_proyecto FROM empleados_proyecto EP
        JOIN empleados E ON EP.id_empleado = E.id_empleado
        JOIN proyectos P ON EP.id_proyecto = P.id_proyecto
        WHERE E.rut_empleado = '11514618-1' AND P.nombre_proyecto = 'Gestión Inventario'));